# Generated by Django 5.0.4 on 2024-05-12 10:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id_shoes', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sh_name', models.CharField(max_length=255)),
                ('sh_model', models.CharField(max_length=255)),
                ('sh_size_array', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('sh_color', models.CharField(max_length=255)),
                ('sh_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('sh_count', models.IntegerField(default=1)),
                ('sh_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sh_image', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'shoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('u_username', models.CharField(max_length=255)),
                ('u_name', models.CharField(max_length=255)),
                ('u_surname', models.CharField(max_length=255)),
                ('u_email', models.CharField(blank=True, max_length=255, null=True)),
                ('u_phone', models.CharField(max_length=13)),
                ('u_status', models.BooleanField(default=False)),
                ('u_role', models.CharField(choices=[('administrator', 'administrator'), ('user', 'user')], default='user', max_length=45)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ShoesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager_app.shoes')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id_reservation', models.IntegerField(primary_key=True, serialize=False)),
                ('r_count', models.IntegerField(default=1)),
                ('r_start_date', models.DateTimeField(auto_now_add=True)),
                ('r_end_date', models.DateTimeField()),
                ('r_shoes', models.ForeignKey(db_column='r_shoes', on_delete=django.db.models.deletion.CASCADE, to='manager_app.shoes')),
                ('r_user', models.ForeignKey(db_column='r_user', on_delete=django.db.models.deletion.CASCADE, to='manager_app.users')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.IntegerField(primary_key=True, serialize=False)),
                ('o_count', models.IntegerField(default=1)),
                ('o_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('o_recipient', models.CharField(default='Name,Surname', max_length=45)),
                ('o_address', models.CharField(default='Address', max_length=100)),
                ('o_comment', models.CharField(max_length=100, null=True)),
                ('o_status', models.CharField(choices=[('Прийнято', 'accepted'), ('Оплачено', 'paid'), ('В обробці', 'in_processing'), ('Відправлено', 'shipped'), ('Доставлено', 'delivered'), ('Оплачено поставнику', 'paid_to_dropper')], max_length=45)),
                ('o_shoes', models.ForeignKey(db_column='o_shoes', on_delete=django.db.models.deletion.CASCADE, to='manager_app.shoes')),
                ('o_user', models.ForeignKey(db_column='o_user', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_app.users')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
